// config.bin - 18:57:51 08/16/15, generated in 0.01 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class TTT_RQ4A {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"ttt_main","ttt_vehicles"};
	};
};
class RscControlsGroup;	// External class reference
class RscText;	// External class reference

class RangeText : RscText {};
class RscPicture;	// External class reference
class RscOpticsText;	// External class reference
class RscIGProgress;	// External class reference
class RscOpticsValue;	// External class reference

class RscInGameUI {
	class RscUnitInfo;	// External class reference
	
	class Rsc_TTT_RQ4A_Turret_UI : RscUnitInfo {
		idd = 300;
		controls[] = {"CA_Zeroing", "CA_IGUI_elements_group", "CA_VehicleToggles"};
		class VScrollbar;	// External class reference
		class HScrollbar;	// External class reference
		
		class CA_IGUI_elements_group : RscControlsGroup {
			idc = 170;
			
			class VScrollbar : VScrollbar {
				width = 0;
			};
			
			class HScrollbar : HScrollbar {
				height = 0;
			};
			x = "0 * 		(0.01875 * SafezoneH) + 		(SafezoneX + ((SafezoneW - SafezoneH) / 2))";
			y = "0 * 		(0.025 * SafezoneH) + 		(SafezoneY)";
			w = "53.5 * 		(0.01875 * SafezoneH)";
			h = "40 * 		(0.025 * SafezoneH)";
			
			class controls {
				class CA_Distance : RscText {
					idc = 151;
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					font = "EtelkaMonospacePro";
					x = "24.78 * 		(0.01875 * SafezoneH)";
					y = "30.88 * 		(0.025 * SafezoneH)";
					w = "4 * 		(0.01875 * SafezoneH)";
					h = "1.2 * 		(0.025 * SafezoneH)";
				};
				
				class CA_Speed : RangeText {
					idc = 188;
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					font = "EtelkaMonospacePro";
					text = 120;
					x = "14.78 * 		(0.01875 * SafezoneH)";
					y = "30.88 * 		(0.025 * SafezoneH)";
					w = "4 * 		(0.01875 * SafezoneH)";
					h = "1.2 * 		(0.025 * SafezoneH)";
				};
				
				class CA_Alt : RangeText {
					idc = 189;
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					font = "EtelkaMonospacePro";
					text = 3825;
					x = "34.78 * 		(0.01875 * SafezoneH)";
					y = "30.88 * 		(0.025 * SafezoneH)";
					w = "4 * 		(0.01875 * SafezoneH)";
					h = "1.2 * 		(0.025 * SafezoneH)";
				};
				
				class ValueTime : RangeText {
					idc = 190;
					text = 20:28:35;
					font = "EtelkaMonospacePro";
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					x = "1.75 * 		(0.01875 * SafezoneH)";
					y = "10.5 * 		(0.025 * SafezoneH)";
					w = "6 * 		(0.01875 * SafezoneH)";
					h = "1 * 		(0.025 * SafezoneH)";
				};
				
				class CA_VisionMode : RscText {
					idc = 152;
					style = 0;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					font = "EtelkaMonospacePro";
					text = VIS;
					align = "right";
					x = "2.6 * 		(0.01875 * SafezoneH)";
					y = "12.0 * 		(0.025 * SafezoneH)";
					w = "4 * 		(0.01875 * SafezoneH)";
					h = "1.0 * 		(0.025 * SafezoneH)";
				};
				
				class CA_FlirMode : RscText {
					idc = 153;
					style = 0;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					font = "EtelkaMonospacePro";
					text = BHOT;
					align = "right";
					x = "6.18 * 		(0.01875 * SafezoneH)";
					y = "12.0 * 		(0.025 * SafezoneH)";
					w = "4.5 * 		(0.01875 * SafezoneH)";
					h = "1.0 * 		(0.025 * SafezoneH)";
				};
				
				class TgT_Grid_text : RangeText {
					idc = 1005;
					text = "TGT:";
					font = "EtelkaMonospacePro";
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					x = "1.20 * 		(0.01875 * SafezoneH)";
					y = "13.5 * 		(0.025 * SafezoneH)";
					w = "6 * 		(0.01875 * SafezoneH)";
					h = "1 * 		(0.025 * SafezoneH)";
				};
				
				class TGT_ValueGrid : RangeText {
					idc = 172;
					font = "EtelkaMonospacePro";
					colorText[] = {0.706, 0.0745, 0.0196, 0.8};
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					x = "5.20 * 		(0.01875 * SafezoneH)";
					y = "13.5 * 		(0.025 * SafezoneH)";
					w = "6 * 		(0.01875 * SafezoneH)";
					h = "1 * 		(0.025 * SafezoneH)";
				};
				
				class OWN_Grid_text : RangeText {
					idc = 1005;
					text = "OWN:";
					font = "EtelkaMonospacePro";
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					x = "1.20 * 		(0.01875 * SafezoneH)";
					y = "15 * 		(0.025 * SafezoneH)";
					w = "6 * 		(0.01875 * SafezoneH)";
					h = "1 * 		(0.025 * SafezoneH)";
				};
				
				class OWN_ValueGrid : RangeText {
					idc = 171;
					font = "EtelkaMonospacePro";
					colorText[] = {0.15, 1, 0.15, 0.8};
					style = 2;
					sizeEx = "0.0295*SafezoneH";
					shadow = 0;
					x = "5.20 * 		(0.01875 * SafezoneH)";
					y = "15 * 		(0.025 * SafezoneH)";
					w = "6 * 		(0.01875 * SafezoneH)";
					h = "1 * 		(0.025 * SafezoneH)";
				};
				
				class CA_Laser : RscText {
					idc = 158;
					style = 0x30 + 0x800;
					sizeEx = "0.038*SafezoneH";
					shadow = 0;
					align = "right";
					font = "EtelkaMonospacePro";
					text = "\TTT_RQ4A\UI\data\Apache_LaserOn.paa";
					x = "20.45 * 		(0.01875 * SafezoneH)";
					y = "14.1 * 		(0.025 * SafezoneH)";
					w = "12.5 * 		(0.01875 * SafezoneH)";
					h = "12 * 		(0.025 * SafezoneH)";
				};
				
				class CA_Heading : RscText {
					idc = 156;
					style = 0;
					sizeEx = "0.038*SafezoneH";
					shadow = 0;
					font = "EtelkaMonospacePro";
					text = 023;
					align = "right";
					x = "25 * 		(0.01875 * SafezoneH)";
					y = "5 * 		(0.025 * SafezoneH)";
					w = "4 * 		(0.01875 * SafezoneH)";
					h = "1.2 * 		(0.025 * SafezoneH)";
				};
			};
		};
	};
};

class CfgVehicles {
	class Plane;	// External class reference
	
	class UAV : Plane {
		class NewTurret;	// External class reference
		class ViewPilot;	// External class reference
		class ViewOptics;	// External class reference
		class AnimationSources;	// External class reference
	};
	
	class TTT_RQ4A : UAV {
		author = TTT;
		displayName = "TTT Aufklärungsdrohne";
		icon = "\A3\Drones_F\Air_F_Gamma\UAV_02\Data\UI\Map_UAV_02_CA.paa";
		picture = "\A3\Drones_F\Air_F_Gamma\UAV_02\Data\UI\UAV_02_base_F.paa";
		vehicleClass = "TTT_Vehicles_us";
		unitInfoType = "RscOptics_AV_pilot";
		attenuationEffectType = "OpenHeliAttenuation";
		_generalMacro = B_UAV_02_F;
		scope = 0;
		side = 1;
		faction = TTT_faction_us;
		crew = B_UAV_AI;
		typicalCargo[] = {B_UAV_AI};
		accuracy = 1;
		soundGetIn[] = {"", 0.562341, 1};
		soundGetOut[] = {"", 0.562341, 1, 40};
		soundDammage[] = {"", 0.562341, 1};
		soundEngineOnInt[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_start_int", 1, 1};
		soundEngineOnExt[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_start_ext", 1.41254, 1, 500};
		soundEngineOffInt[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_stop_int", 1, 1};
		soundEngineOffExt[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_stop_ext", 1.41254, 1, 500};
		soundLocked[] = {"\A3\Sounds_F\weapons\Rockets\locked_1", 0.1, 1};
		soundIncommingMissile[] = {"\A3\Sounds_F\weapons\Rockets\locked_3", 0.1, 1.5};
		soundGearUp[] = {"A3\Sounds_F_EPC\CAS_01\gear_up", 0.794328, 1, 150};
		soundGearDown[] = {"A3\Sounds_F_EPC\CAS_01\gear_down", 0.794328, 1, 150};
		soundFlapsUp[] = {"A3\Sounds_F_EPC\CAS_01\Flaps_Up", 0.630957, 1, 100};
		soundFlapsDown[] = {"A3\Sounds_F_EPC\CAS_01\Flaps_Down", 0.630957, 1, 100};
		
		class Sounds {
			class EngineLowOut {
				sound[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_engine_idle_ext", 1.77828, 1, 2100};
				frequency = "1.0 min (rpm + 0.5)";
				volume = "camPos*2*(rpm factor[0.95, 0])*(rpm factor[0, 0.95])";
			};
			
			class EngineHighOut {
				sound[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_engine_ext", 1.99526, 1.2, 2500};
				frequency = "1";
				volume = "camPos*4*(rpm factor[0.5, 1.1])*(rpm factor[1.1, 0.5])";
			};
			
			class ForsageOut {
				sound[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_forsage_ext", 2.51189, 1.2, 2800};
				frequency = "1";
				volume = "engineOn*camPos*(thrust factor[0.6, 1.0])";
				cone[] = {3.14, 3.92, 2, 0.5};
			};
			
			class WindNoiseOut {
				sound[] = {"A3\Sounds_F\air\Plane_Fighter_03\noise", 0.562341, 1, 150};
				frequency = "(0.1+(1.2*(speed factor[1, 150])))";
				volume = "camPos*(speed factor[1, 150])";
			};
			
			class EngineLowIn {
				sound[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_engine_idle_int", 1, 1};
				frequency = "1.0 min (rpm + 0.5)";
				volume = "(1-camPos)*((rpm factor[0.7, 0.1])*(rpm factor[0.1, 0.7]))";
			};
			
			class EngineHighIn {
				sound[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_engine_int", 1, 1.2};
				frequency = "1";
				volume = "(1-camPos)*(rpm factor[0.85, 1.0])";
			};
			
			class ForsageIn {
				sound[] = {"A3\Sounds_F_EPC\CAS_01\CAS_01_forsage_int", 1, 1.2};
				frequency = "1";
				volume = "(1-camPos)*(engineOn*(thrust factor[0.6, 1.0]))";
			};
			
			class WindNoiseIn {
				sound[] = {"A3\Sounds_F\air\Plane_Fighter_03\noise", 0.501187, 1};
				frequency = "(0.1+(1.2*(speed factor[1, 150])))";
				volume = "(1-camPos)*(speed factor[1, 150])";
			};
		};
		formationX = 30;
		formationZ = 30;
		
		class Armory {
			description = "$STR_A3_CfgVehicles_UAV_02_base_Armory0";
		};
		model = "\TTT_RQ4A\TTT_RQ4A.p3d";
		driveOnComponent[] = {"wheel_1", "wheel_2", "wheel_3"};
		
		class TransportItems {};
		uavCameraDriverPos = "PiP0_pos";
		uavCameraDriverDir = "PiP0_dir";
		uavCameraGunnerPos = "mainturret";
		uavCameraGunnerDir = "maingun";
		memoryPointLDust = "DustLeft";
		memoryPointRDust = "DustRight";
		memoryPointDriverOptics = "PiP0_pos";
		driverOpticsModel = "A3\drones_f\Weapons_F_Gamma\Reticle\UGV_01_Optics_Driver_F.p3d";
		driverForceOptics = 1;
		
		class WingVortices {};
		
		class ViewPilot : ViewPilot {
			initFov = 1;
			minFov = 0.3;
			maxFov = 1.2;
			initAngleX = 0;
			minAngleX = -65;
			maxAngleX = 85;
			initAngleY = 0;
			minAngleY = -150;
			maxAngleY = 150;
		};
		
		class Viewoptics : ViewOptics {
			initAngleX = 0;
			minAngleX = 0;
			maxAngleX = 0;
			initAngleY = 0;
			minAngleY = 0;
			maxAngleY = 0;
			initFov = 1;
			minFov = 0.3;
			maxFov = 1.2;
			visionMode[] = {"Normal", NVG, "Ti"};
			thermalMode[] = {0, 1};
		};
		
		class AnimationSources : AnimationSources {
			class Bombs {
				source = "user";
				animPeriod = 1e-006;
				initPhase = 0;
			};
			
			class AT_missiles {
				source = "user";
				animPeriod = 0.99;
				initPhase = 1;
			};
		};
		maxSpeed = 500;
		envelope[] = {0, 0.3, 1.15, 2.2, 4.35, 5.2, 6, 6.55, 6.65, 6.8, 3.6, 1.8, 0};
		landingSpeed = 100;
		altFullForce = 7000;
		altNoForce = 14000;
		aileronSensitivity = 1.5;
		elevatorSensitivity = 0.9;
		wheelSteeringSensitivity = 5;
		rudderInfluence = 0.01;
		rudderControlsSensitivitycoef = 4;
		rudderCoef[] = {0.6, 1, 1, 0.9, 0.8, 0.7, 0.6};
		killFriendlyExpCoef = 0.1;
		driverCompartments = "Compartment3";
		cargoCompartments[] = {"Compartment2"};
		
		class Damage {
			tex[] = {};
			mat[] = {"A3\Drones_F\Air_F_Gamma\UAV_02\Data\UAV_02.rvmat", "A3\Drones_F\Air_F_Gamma\UAV_02\Data\UAV_02_damage.rvmat", "A3\Drones_F\Air_F_Gamma\UAV_02\Data\UAV_02_destruct.rvmat"};
		};
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"A3\Drones_F\Air_F_Gamma\UAV_02\Data\UAV_02_CO.paa"};
		weapons[] = {};
		magazines[] = {};
		LockDetectionSystem = 1 + 8 + 4;
		incomingMissileDetectionSystem = 16;
		laserscanner = 1;
		DriverCanSee = 1 + 2 + 4 + 8 + 16;
		
		class Turrets {
			class MainTurret : NewTurret {
				isCopilot = 0;
				minElev = -85;
				maxElev = 10;
				initElev = 0;
				minTurn = -360;
				maxTurn = 360;
				initTurn = 0;
				outGunnerMayFire = "true";
				inGunnerMayFire = "true";
				commanding = -1;
				body = "mainTurret";
				gun = "mainGun";
				animationSourceBody = "mainTurret";
				animationSourceGun = "mainGun";
				memoryPointGun = "mainGun";
				memoryPointGunnerOptics = "mainGun";
				gunBeg = "laserend";
				gunEnd = "laserstart";
				gunnerOpticsModel = "A3\drones_f\Weapons_F_Gamma\Reticle\UGV_01_Optics_Gunner_F.p3d";
				gunnerOpticsEffect[] = {"TankCommanderOptics1", "BWTVedit"};
				gunnerForceOptics = "true";
				turretInfoType = "Rsc_TTT_RQ4A_Turret_UI";
				turretCanSee = 1 + 2 + 4 + 8 + 16;
				stabilizedInAxes = 3;
				enableManualFire = 0;
				weapons[] = {"Laserdesignator_mounted"};
				magazines[] = {"Laserbatteries"};
				GunnerCompartments = "Compartment1";
				gunnerInAction = "Disabled";
				gunnerAction = "Disabled";
				
				class OpticsIn {
					class WideNGS {
						opticsDisplayName = "W";
						initAngleX = 0;
						minAngleX = -35;
						maxAngleX = 10;
						initAngleY = 0;
						minAngleY = -100;
						maxAngleY = 100;
						initFov = 0.466;
						minFov = 0.466;
						maxFov = 0.466;
						visionMode[] = {"Normal", NVG, "Ti"};
						thermalMode[] = {0, 1};
						gunnerOpticsColor[] = {0.15, 1, 0.15, 1};
						gunnerOpticsModel = "A3\Weapons_F\Reticle\Optics_Gunner_MBT_03_w_F.p3d";
						directionStabilized = 0;
						opticsPPEffects[] = {"OpticsCHAbera2", "OpticsBlur2"};
					};
					
					class Wide {
						opticsDisplayName = "W";
						initAngleX = 0;
						minAngleX = -35;
						maxAngleX = 10;
						initAngleY = 0;
						minAngleY = -100;
						maxAngleY = 100;
						initFov = 0.466;
						minFov = 0.466;
						maxFov = 0.466;
						visionMode[] = {"Normal", NVG, "Ti"};
						thermalMode[] = {0, 1};
						gunnerOpticsColor[] = {0.15, 1, 0.15, 1};
						gunnerOpticsModel = "A3\Weapons_F\Reticle\Optics_Gunner_MBT_02_w_F.p3d";
						directionStabilized = 1;
						opticsPPEffects[] = {"OpticsCHAbera2", "OpticsBlur2"};
						gunnerOpticsEffect[] = {"TankCommanderOptics1", "BWTVedit"};
					};
					
					class WideL : Wide {
						opticsDisplayName = "WL";
						initFov = 0.2;
						minFov = 0.2;
						maxFov = 0.2;
						gunnerOpticsModel = "A3\Weapons_F\Reticle\Optics_Gunner_MBT_02_m_F.p3d";
						gunnerOpticsColor[] = {0, 0, 0, 1};
						directionStabilized = 1;
						opticsPPEffects[] = {"OpticsCHAbera2", "OpticsBlur2"};
					};
					
					class Medium : Wide {
						opticsDisplayName = "M";
						initFov = 0.1;
						minFov = 0.1;
						maxFov = 0.1;
						directionStabilized = 1;
						gunnerOpticsColor[] = {0, 0, 0, 1};
						gunnerOpticsModel = "A3\Weapons_F\Reticle\Optics_Gunner_MBT_02_m_F.p3d";
					};
					
					class Narrow : Wide {
						opticsDisplayName = "N";
						gunnerOpticsColor[] = {0, 0, 0, 1};
						gunnerOpticsModel = "A3\Weapons_F\Reticle\Optics_Gunner_MBT_02_n_F.p3d";
						directionStabilized = 1;
						initFov = 0.02;
						minFov = 0.02;
						maxFov = 0.02;
					};
					
					class Narrower : Wide {
						opticsDisplayName = "N";
						gunnerOpticsColor[] = {0, 0, 0, 1};
						gunnerOpticsModel = "A3\Weapons_F\Reticle\Optics_Gunner_MBT_02_n_F.p3d";
						directionStabilized = 1;
						initFov = 0.01;
						minFov = 0.01;
						maxFov = 0.01;
					};
				};
				
				class OpticsOut {
					class Monocular {
						initAngleX = 0;
						minAngleX = -30;
						maxAngleX = 30;
						initAngleY = 0;
						minAngleY = -100;
						maxAngleY = 100;
						initFov = 1.1;
						minFov = 0.133;
						maxFov = 1.1;
						visionMode[] = {"Normal", NVG};
						gunnerOpticsModel = "";
						gunnerOpticsEffect[] = {};
					};
				};
			};
		};
		
		class Reflectors {
			class Left {
				color[] = {7000, 7500, 10000, 1};
				ambient[] = {100, 100, 100, 0};
				position = "light_1_pos";
				direction = "light_1_dir";
				hitpoint = "L svetlo";
				selection = "L svetlo";
				size = 1;
				innerAngle = 20;
				outerAngle = 60;
				coneFadeCoef = 10;
				intensity = 50;
				useFlare = 1;
				dayLight = 0;
				FlareSize = 4;
				
				class Attenuation {
					start = 1;
					constant = 0;
					linear = 0;
					quadratic = 4;
				};
			};
		};
		
		class MarkerLights {
			class RedStill {
				name = "cerveny pozicni";
				color[] = {0.8, 0, 0};
				ambient[] = {0.08, 0, 0};
				intensity = 75;
				drawLight = 1;
				drawLightSize = 0.15;
				drawLightCenterSize = 0.04;
				activeLight = 0;
				blinking = 0;
				dayLight = 0;
				useFlare = 0;
			};
			
			class GreenStill {
				name = "zeleny pozicni";
				color[] = {0, 0.8, 0};
				ambient[] = {0, 0.08, 0};
				intensity = 75;
				drawLight = 1;
				drawLightSize = 0.15;
				drawLightCenterSize = 0.04;
				activeLight = 0;
				blinking = 0;
				dayLight = 0;
				useFlare = 0;
			};
			
			class WhiteBlinking {
				name = "bily pozicni blik";
				color[] = {1, 1, 1, 1};
				ambient[] = {0.2, 0.2, 0.2, 1};
				intensity = 75;
				blinking = 1;
				blinkingPattern[] = {0.1, 0.9};
				blinkingPatternGuarantee = 0;
				drawLightSize = 0.2;
				drawLightCenterSize = 0.04;
			};
			
			class WhiteBlinking2 {
				name = "bily pozicni blik2";
				color[] = {1, 1, 1, 1};
				ambient[] = {0.2, 0.2, 0.2, 1};
				intensity = 75;
				blinking = 1;
				blinkingPattern[] = {0.1, 0.9};
				blinkingPatternGuarantee = 0;
				drawLightSize = 0.2;
				drawLightCenterSize = 0.04;
			};
		};
	};
};
