#define COMPONENT advancedslingloading
#define COMPONENT_BEAUTIFIED Advanced Slingloading

#include "\z\ttt\addons\main\script_mod.hpp"
#include "\z\ttt\addons\main\script_macros.hpp"

// Magic numbers
#define ASL_NEARBY_VEHICLE_DISTANCE 30
#define ASL_ROPE_PROXIMITY_DISTANCE 5
#define ASL_PICKUP_DISTANCE 10
#define ASL_PLAYER_DISTANCE 30
#define ASL_ROPE_UNWIND_SPEED 5
#define ASL_DEFAULT_ROPE_LENGTH 15
#define ASL_ROPE_LENGTH_STEP 5
#define ASL_HEAVY_LIFT_MIN_LIFT 4000
#define ASL_HEAVY_LIFT_MASS_FACTOR 0.8
#define ASL_HEIGHT_DIVISOR 6
#define ASL_WIDTH_FACTOR_DEFAULT 0.5
#define ASL_WIDTH_FACTOR_AIR 0.3
#define ASL_WIDTH_FACTOR_HELI 0.2
#define ASL_LENGTH_FACTOR_DEFAULT 0.5
#define ASL_LENGTH_FACTOR_HELI 0.45
#define ASL_ROPE_DISTANCE_THRESHOLD 2
#define ASL_HEAVY_LIFT_SLEEP_TIME 0.1
#define ASL_HEAVY_LIFT_WAIT_TIME 0.5
#define ASL_NEARBY_CHECK_INTERVAL 2
