// ACE Name Tags
force force ace_nametags_ambientBrightnessAffectViewDist = 0.5;
ace_nametags_defaultNametagColor = [0.77,0.51,0.08,1];
ace_nametags_nametagColorBlue = [0,0,1,1];
ace_nametags_nametagColorGreen = [0,1,0,1];
ace_nametags_nametagColorMain = [1,1,1,1];
ace_nametags_nametagColorRed = [1,0,0,1];
ace_nametags_nametagColorYellow = [1,1,0,1];
force force ace_nametags_playerNamesMaxAlpha = 0.8;
force force ace_nametags_playerNamesViewDistance = 8;
force force ace_nametags_showCursorTagForVehicles = false;
force force ace_nametags_showNamesForAI = true;
force force ace_nametags_showPlayerNames = 1;
force force ace_nametags_showPlayerRanks = true;
force force ace_nametags_showSoundWaves = 1;
force force ace_nametags_showVehicleCrewInfo = false;
ace_nametags_tagSize = 2;
