// Advanced Sling Loading
force prae_asl_setting_allowedRopeClasses = "ACE_rope3,ACE_rope6,ACE_rope12,ACE_rope15,ACE_rope18,ACE_rope27,ACE_rope36";
force prae_asl_setting_allowGroundCrewInventory = true;
force prae_asl_setting_allowHelicopterCargo = true;
force prae_asl_setting_allowPilotInventory = true;
force prae_asl_setting_dualLoadHelicopterClasses = "B_Heli_Transport_03_F,B_Heli_Transport_03_unarmed_F,O_Heli_Transport_04_F,O_Heli_Transport_04_box_F,O_Heli_Transport_04_covered_F,O_Heli_Transport_04_fuel_F,O_Heli_Transport_04_medevac_F,O_Heli_Transport_04_repair_F,O_Heli_Transport_04_ammo_F";
force prae_asl_setting_enabled = true;
force prae_asl_setting_groundInteractionDistance = 10;
force prae_asl_setting_liftFactor = 1;
force prae_asl_setting_requireRopeItem = true;
force prae_asl_setting_ropeLength = 15;
force prae_asl_setting_ropeReturnMaxHeliHeight = 4;
