// Hatchet Vehicle Framework
hct_interaction_autoclose_actionmenu = false;
hct_interaction_cursorColor = [0.6,0.84,0.47,1];
hct_interaction_cursorText = "Ã—";
hct_interaction_pointing = true;
hct_interaction_showDebugMessages = false;
hct_interaction_showLabels = 2;
hct_interaction_trackIR_interaction_cursor = false;
hct_interaction_trackIR_interaction_cursor_invert = false;
hct_interaction_trackIR_interaction_cursorSensitivity = 2.5;
hct_interaction_updateEvery = 5;
