// Metis Enhanced
force force mts_armory_allowPlayerDBConnection = false;
force force mts_armory_openUIActionMenu = "ace_interaction";
force force mts_cutter_bushcutter_duration = 10;
force force mts_cutter_bushcutter_enabled = true;
force force mts_cutter_bushcutter_requireItem = true;
force force mts_cutter_grasscutter_duration = 5;
force force mts_cutter_grasscutter_enabled = true;
force force mts_cutter_grasscutter_size = 1;
force force mts_drill_UIEnabled = false;
mts_zeus_ACEUnconsciousIconColor = [0.9,0,0,1];
mts_zeus_comments_3DENColor = [0,1,0.75,0.7];
mts_zeus_comments_allowDeleting3DEN = false;
mts_zeus_comments_enabled = true;
mts_zeus_comments_enabled3DEN = true;
mts_zeus_enableACEUnconsciousIcon = true;
mts_zeus_plotting_color = [0.9,0.9,0,1];

// Metis Enhanced - Chat Commands
force force mts_chat_commands_adveng = "admin";
force force mts_chat_commands_doctor = "admin";
force force mts_chat_commands_eng = "admin";
force force mts_chat_commands_heal = "admin";
force force mts_chat_commands_healall = "admin";
force force mts_chat_commands_markers = "admin";
force force mts_chat_commands_medic = "admin";
force force mts_chat_commands_repair = "admin";
force force mts_chat_commands_teleport = "admin";
force force mts_chat_commands_zeus = "admin";

// Metis Marker
mts_markers_defaultMarkerAlpha = 1;
mts_markers_defaultMarkerScale = 1.3;
mts_markers_displayShortDTG = true;
mts_markers_saveLastSelection = false;
mts_markers_useVanillaColors = false;
