// TSP Breach
force force tsp_cba_breach = true;
force force tsp_cba_breach_ace = true;
force tsp_cba_breach_ammo = "[""B_12Gauge_Slug_NoCartridge"",""B_12Gauge_Pellets_Submunition"",""ACE_12Gauge_Pellets_Submunition_No0_Buck"",""rhs_ammo_12g_slug"",""rhs_ammo_12g_00buckshot"",""rhs_ammo_m576_buckshot"",""UK3CB_BAF_B_12Gauge_Slug"",""CUP_12Gauge_Slug"",""CUP_B_12Gauge_Pellets"",""CUP_B_12Gauge_74Slug"",""CUP_12Gauge_Pellets_Submunition_No0_Buck"",""CUP_12Gauge_Pellets_Submunition_No00_Buck"",""UK3CB_BAF_B_12Gauge_Pellets"",""HLC_12G_Buck""]";
force tsp_cba_breach_ammo_multiplier = 0;
force force tsp_cba_breach_auto = 5;
force force tsp_cba_breach_break = true;
force force tsp_cba_breach_fuse = 3;
force tsp_cba_breach_lock_blacklist = "[]";
force force tsp_cba_breach_lock_door = 0;
force force tsp_cba_breach_lock_house = 0;
force force tsp_cba_breach_lockpick = "[0,0.75,0.5,0.05]";
force tsp_cba_breach_military = "[]";
force force tsp_cba_breach_paperclip = "[0,0.5,0.25,0.15]";
force force tsp_cba_breach_picking_time = 20;
force force tsp_cba_breach_ragdoll_distance = 5;
force force tsp_cba_breach_ragdoll_force = 1;
force tsp_cba_breach_reinforced = "[]";
force force tsp_cba_breach_shock = 240;
force force tsp_cba_breach_stun = false;
force force tsp_cba_breach_vanilla = false;
force tsp_cba_breach_walls = "[
[""AHHH"", ""Land_BrickWall_04_l_5m_F"",""Land_BrickWall_04_l_5m_d_F""],
[""AHHH"", ""Land_BrickWall_03_l_5m_v2_F"",""Land_BrickWall_03_l_5m_v2_d_F""],
[""AHHH"", ""Land_BrickWall_03_l_5m_v1_F"",""Land_BrickWall_03_l_5m_v2_d_F""],
[""AHHH"", ""Land_BrickWall_02_l_5m_F"",""Land_BrickWall_02_l_5m_d_F""],
[""AHHH"", ""Land_BrickWall_01_l_5m_F"",""Land_BrickWall_01_l_5m_d_F""],
[""AHHH"", ""Land_Stone_8m_F"",""Land_Stone_8mD_F""],
[""AHHH"", ""Land_WallCity_01_8m_yellow_F"",""Land_WallCity_01_8m_dmg_yellow_F""],
[""AHHH"", ""Land_City_8m_F"",""Land_City_8mD_F""],
[""AHHH"", ""Land_WallCity_01_8m_whiteblue_F"",""Land_WallCity_01_8m_dmg_whiteblue_F""],
[""AHHH"", ""Land_WallCity_01_8m_blue_F"",""Land_WallCity_01_8m_dmg_blue_F""],
[""AHHH"", ""Land_WallCity_01_8m_grey_F"",""Land_WallCity_01_8m_dmg_grey_F""],
[""AHHH"", ""Land_WallCity_01_8m_pink_F"",""Land_WallCity_01_8m_dmg_pink_F""],
[""AHHH"", ""Land_SilageWall_01_l_5m_F"",""Land_SilageWall_01_l_d_F""],
[""AHHH"", ""Land_ConcreteWall_02_m_8m_F"",""Land_ConcreteWall_02_m_d_F""],
[""AHHH"", ""Land_ConcreteWall_01_m_4m_F"",""Land_ConcreteWall_01_m_d_F""],
[""AHHH"", ""Land_ConcreteWall_01_m_8m_F"",""Land_ConcreteWall_01_m_d_F""],
[""AHHH"", ""Land_PipeFence_01_m_8m_F"",""Land_PipeFence_01_m_d_F""],
[""AHHH"", ""Land_City2_8m_F"",""Land_City2_8mD_F""],
[""AHHH"", ""Land_Wall_IndCnc_4_F"",""Land_Wall_IndCnc_End_2_F""],
[""AHHH"", ""Land_CamoConcreteWall_01_l_4m_v1_F"",""Land_CamoConcreteWall_01_l_end_v1_F""],
[""AHHH"", ""Land_Mil_WallBig_4m_F"",""Land_Mil_WallBig_4m_damaged_center_F""],
[""mil_wallbig_4m_battered_f"", ""Land_Mil_WallBig_4m_battered_F"",""Land_Mil_WallBig_4m_damaged_right_F""],
[""AHHH"", ""Land_Mil_WallBig_Corner_F"",""Land_Mil_WallBig_debris_F""],
[""AHHH"", ""Land_Mil_WallBig_corner_battered_F"",""Land_Mil_WallBig_debris_F""]
]";

// TSP Breach - Flashbang
force force tsp_cba_flashbang_brightness = 1;
force force tsp_cba_flashbang_distance = 10;
force force tsp_cba_flashbang_fire = true;
force force tsp_cba_flashbang_friends = 0.1;
force force tsp_cba_flashbang_intensity = 1;
force force tsp_cba_flashbang_smoke = true;
force force tsp_cba_flashbang_sparks = true;
force force tsp_cba_flashbang_spray = 0.4;
force force tsp_cba_flashbang_surrender = 0.1;
force force tsp_cba_flashbang_volume = 5;

// TSP Core
force force tsp_cba_angle = -0.1;
force force tsp_cba_compat = false;
force force tsp_cba_core_chvd = false;
force force tsp_cba_core_pause = false;
tsp_cba_hint = "ACE";
tsp_cba_hint_distance = 20;
force force tsp_param_faction = false;
