// Tactical Training Team
force ttt_compat_rnt_lafetteDisassembleTime = 10;
force ttt_compat_rnt_lafetteMountTime = 5;

ttt_discord_richpresence_enableDRP = true;

force ttt_dismantle_enable = false;
force ttt_dismantle_neededItem = "";
force ttt_dismantle_neededSkill = 1;
force ttt_dismantle_supportedObjects = "[]";

force ttt_medic_backpack_additionalItems = "[]";
force ttt_medic_backpack_buildAnimation = "Acts_carFixingWheel";
force ttt_medic_backpack_buildTime = 20;
force ttt_medic_backpack_enable = false;
force ttt_medic_backpack_facilityObject = "Land_MedicalTent_01_floor_dark_F";
force ttt_medic_backpack_supportedBackpacks = "[]";
force ttt_medic_backpack_useAnimation = true;
force ttt_medic_vehicle_buildAnimation = "Acts_carFixingWheel";
force ttt_medic_vehicle_buildTime = 30;
force ttt_medic_vehicle_enable = false;
force ttt_medic_vehicle_facilityObject = "Land_MedicalTent_01_NATO_generic_open_F";
force ttt_medic_vehicle_supportedVehicles = "[]";
force ttt_medic_vehicle_useAnimation = true;

force ttt_repair_vehicle_buildAnimation = "Acts_carFixingWheel";
force ttt_repair_vehicle_buildTime = 30;
force ttt_repair_vehicle_enable = false;
force ttt_repair_vehicle_facilityObject = "Land_RepairDepot_01_green_F";
force ttt_repair_vehicle_supportedVehicles = "[]";
force ttt_repair_vehicle_useAnimation = true;

force ttt_signalpanel_buildTime = 6;
force ttt_signalpanel_enable = false;
force ttt_signalpanel_supportedBackpacks = "[]";

force ttt_teleport_enableJIPMoveToRespawn = true;
force ttt_teleport_enableTeleport = true;
