PREP(addActions);
PREP(classifyMag);
PREP(decrementCrateLimit);
PREP(getCrateLimit);
PREP(isCrateAvailable);
PREP(resolveDisposableLauncher);
PREP(scanLoadouts);
PREP(spawnCrate);
PREP(zeusPlaceCrate);
