#define SUBCOMPONENT mg3
#define SUBCOMPONENT_BEAUTIFIED MG3
#include "..\script_component.hpp"

#define MIN_DURATION 1
#define MAX_DURATION 120
#define TRAILING_DECIMALS 0
#define IS_SERVER_SETTINGS 1
#define MG_MOUNT_TIME 5
#define DISASSEMBLE_TIME 10