//by Highhead & TheConen for TTT
//tacticalteam.de
class CfgPatches {
	class ttt_units_bw_c {
		units[] = {	"TTT_Gelb1_Bw_Tropentarn",
					"TTT_Gelb2_Bw_Tropentarn",
					"TTT_Gelb3_Bw_Tropentarn",
					"TTT_Gelb4_Bw_Tropentarn",

					"TTT_Grau1_Bw_Tropentarn",
					"TTT_Grau2_Bw_Tropentarn",
					"TTT_Grau3_Bw_Tropentarn",
					"TTT_Grau4_Bw_Tropentarn",
					"TTT_Grau5_Bw_Tropentarn",
					"TTT_Grau6_Bw_Tropentarn",

					"TTT_Gold1_Bw_Tropentarn",
					"TTT_Gold2_Bw_Tropentarn",
					"TTT_Gold3_Bw_Tropentarn",
					"TTT_Gold4_Bw_Tropentarn",

					"TTT_Gruen1_Bw_Tropentarn",
					"TTT_Gruen2_Bw_Tropentarn",
					"TTT_Gruen3_Bw_Tropentarn",
					"TTT_Gruen4_Bw_Tropentarn",

					"TTT_Braun1_Bw_Tropentarn",
					"TTT_Braun2_Bw_Tropentarn",
					"TTT_Braun3_Bw_Tropentarn",

					"TTT_Schwarz1_Bw_Tropentarn",
					"TTT_Schwarz2_Bw_Tropentarn",
					"TTT_Schwarz3_Bw_Tropentarn",
					"TTT_Schwarz4_Bw_Tropentarn",
					"TTT_Schwarz5_Bw_Tropentarn",
					"TTT_Schwarz6_Bw_Tropentarn",

					"TTT_Rot1_Bw_Tropentarn",
					"TTT_Rot2_Bw_Tropentarn",
					"TTT_Rot3_Bw_Tropentarn",
					"TTT_Rot4_Bw_Tropentarn",
					"TTT_Rot5_Bw_Tropentarn",
					"TTT_Rot6_Bw_Tropentarn",

					"TTT_Bronze1_Bw_Tropentarn",
					"TTT_Bronze2_Bw_Tropentarn",
					"TTT_Bronze3_Bw_Tropentarn",

					"TTT_Blau1_Bw_Tropentarn",
					"TTT_Blau2_Bw_Tropentarn",
					"TTT_Blau3_Bw_Tropentarn",
					"TTT_Blau4_Bw_Tropentarn",
					"TTT_Blau5_Bw_Tropentarn",
					"TTT_Blau6_Bw_Tropentarn",

					"TTT_Violett1_Bw_Tropentarn",
					"TTT_Violett2_Bw_Tropentarn",
					"TTT_Violett3_Bw_Tropentarn",
					"TTT_Violett4_Bw_Tropentarn",
					"TTT_Violett5_Bw_Tropentarn",
					"TTT_Violett6_Bw_Tropentarn",

					"TTT_Weiss1_Bw_Tropentarn",
					"TTT_Weiss2_Bw_Tropentarn",
					"TTT_Weiss3_Bw_Tropentarn",
					"TTT_Adler1_Bw_Tropentarn",
					"TTT_Adler2_Bw_Tropentarn",

					"TTT_Bussard1_Bw_Tropentarn",
					"TTT_Bussard2_Bw_Tropentarn",
					"TTT_Habicht1_Bw_Tropentarn",
					"TTT_Habicht2_Bw_Tropentarn",

					"TTT_Gelb_Bw_Tropentarn",
					"TTT_Grau_Bw_Tropentarn",
					"TTT_Gold_Bw_Tropentarn",
					"TTT_Gruen_Bw_Tropentarn",
					"TTT_Braun_Bw_Tropentarn",
					"TTT_Schwarz_Bw_Tropentarn",
					"TTT_Rot_Bw_Tropentarn",
					"TTT_Bronze_Bw_Tropentarn",
					"TTT_Blau_Bw_Tropentarn",
					"TTT_Violett_Bw_Tropentarn",
					"TTT_Weiss_Bw_Tropentarn",
					"TTT_Adler_Bw_Tropentarn",
					"TTT_Bussard_Bw_Tropentarn",
					"TTT_Habicht_Bw_Tropentarn",

					"TTT_Gelb1_Bw_Flecktarn",
					"TTT_Gelb2_Bw_Flecktarn",
					"TTT_Gelb3_Bw_Flecktarn",
					"TTT_Gelb4_Bw_Flecktarn",

					"TTT_Grau1_Bw_Flecktarn",
					"TTT_Grau2_Bw_Flecktarn",
					"TTT_Grau3_Bw_Flecktarn",
					"TTT_Grau4_Bw_Flecktarn",
					"TTT_Grau5_Bw_Flecktarn",
					"TTT_Grau6_Bw_Flecktarn",

					"TTT_Gold1_Bw_Flecktarn",
					"TTT_Gold2_Bw_Flecktarn",
					"TTT_Gold3_Bw_Flecktarn",
					"TTT_Gold4_Bw_Flecktarn",

					"TTT_Gruen1_Bw_Flecktarn",
					"TTT_Gruen2_Bw_Flecktarn",
					"TTT_Gruen3_Bw_Flecktarn",
					"TTT_Gruen4_Bw_Flecktarn",

					"TTT_Braun1_Bw_Flecktarn",
					"TTT_Braun2_Bw_Flecktarn",
					"TTT_Braun3_Bw_Flecktarn",

					"TTT_Schwarz1_Bw_Flecktarn",
					"TTT_Schwarz2_Bw_Flecktarn",
					"TTT_Schwarz3_Bw_Flecktarn",
					"TTT_Schwarz4_Bw_Flecktarn",
					"TTT_Schwarz5_Bw_Flecktarn",
					"TTT_Schwarz6_Bw_Flecktarn",

					"TTT_Rot1_Bw_Flecktarn",
					"TTT_Rot2_Bw_Flecktarn",
					"TTT_Rot3_Bw_Flecktarn",
					"TTT_Rot4_Bw_Flecktarn",
					"TTT_Rot5_Bw_Flecktarn",
					"TTT_Rot6_Bw_Flecktarn",

					"TTT_Bronze1_Bw_Flecktarn",
					"TTT_Bronze2_Bw_Flecktarn",
					"TTT_Bronze3_Bw_Flecktarn",

					"TTT_Blau1_Bw_Flecktarn",
					"TTT_Blau2_Bw_Flecktarn",
					"TTT_Blau3_Bw_Flecktarn",
					"TTT_Blau4_Bw_Flecktarn",
					"TTT_Blau5_Bw_Flecktarn",
					"TTT_Blau6_Bw_Flecktarn",

					"TTT_Violett1_Bw_Flecktarn",
					"TTT_Violett2_Bw_Flecktarn",
					"TTT_Violett3_Bw_Flecktarn",
					"TTT_Violett4_Bw_Flecktarn",
					"TTT_Violett5_Bw_Flecktarn",
					"TTT_Violett6_Bw_Flecktarn",

					"TTT_Weiss1_Bw_Flecktarn",
					"TTT_Weiss2_Bw_Flecktarn",
					"TTT_Weiss3_Bw_Flecktarn",
					"TTT_Adler1_Bw_Flecktarn",
					"TTT_Adler2_Bw_Flecktarn",

					"TTT_Bussard1_Bw_Flecktarn",
					"TTT_Bussard2_Bw_Flecktarn",
					"TTT_Habicht1_Bw_Flecktarn",
					"TTT_Habicht2_Bw_Flecktarn",

					"TTT_Gelb_Bw_Flecktarn",
					"TTT_Grau_Bw_Flecktarn",
					"TTT_Gold_Bw_Flecktarn",
					"TTT_Gruen_Bw_Flecktarn",
					"TTT_Schwarz_Bw_Flecktarn",
					"TTT_Rot_Bw_Flecktarn",
					"TTT_Bronze_Bw_Flecktarn",
					"TTT_Blau_Bw_Flecktarn",
					"TTT_Weiss_Bw_Flecktarn",
					"TTT_Adler_Bw_Flecktarn",
					"TTT_Bussard_Bw_Flecktarn",
					"TTT_Habicht_Bw_Flecktarn",

					"TTT_Logistik_Waffen_Bw",
					"TTT_Logistik_Spezialwaffen_Bw",
					"TTT_Logistik_Standardmunition_Bw",
					"TTT_Logistik_Spezialmunition_Bw",
					"TTT_Logistik_Pionierausruestung_Bw",
					"TTT_Logistik_Granaten_Bw",
					"TTT_Logistik_Ausruestung_Bw",
					"TTT_Logistik_Werfer_Bw",
					"TTT_Logistik_Werfermunition_Bw",
					"TTT_Logistik_Medic_Rucksaecke_Bw",
					"TTT_Logistik_Medic_Bw",
					"TTT_Logistik_Kiste_Klein_Bw",
					"TTT_Logistik_Kiste_Gross_Bw"
				};
		weapons[] = {
					"TTT_Uniform_Gelb_Bw_Tropentarn",
					"TTT_Uniform_Gruen_Bw_Tropentarn",
					"TTT_Uniform_Braun_Bw_Tropentarn",
					"TTT_Uniform_Rot_Bw_Tropentarn",
					"TTT_Uniform_Schwarz_Bw_Tropentarn",
					"TTT_Uniform_Violett_Bw_Tropentarn",
					"TTT_Uniform_Weiss_Bw_Tropentarn",
					"TTT_Uniform_Blau_Bw_Tropentarn",
					"TTT_Uniform_Grau_Bw_Tropentarn",
					"TTT_Uniform_Gold_Bw_Tropentarn",
					"TTT_Uniform_Silver_Bw_Tropentarn",
					
					"TTT_Uniform_Gelb_Bw_Flecktarn",
					"TTT_Uniform_Gruen_Bw_Flecktarn",
					"TTT_Uniform_Braun_Bw_Flecktarn",
					"TTT_Uniform_Rot_Bw_Flecktarn",
					"TTT_Uniform_Schwarz_Bw_Flecktarn",
					"TTT_Uniform_Blau_Bw_Flecktarn",
					"TTT_Uniform_Violett_Bw_Flecktarn",
					"TTT_Uniform_Weiss_Bw_Flecktarn",
					"TTT_Uniform_Grau_Bw_Flecktarn",
					"TTT_Uniform_Gold_Bw_Flecktarn",
					"TTT_Uniform_Silver_Bw_Flecktarn",
					
					"TTT_Helmet_1_Bw_Tropentarn",
					"TTT_Helmet_2_Bw_Tropentarn",
					"TTT_Helmet_3_Bw_Tropentarn",
					"TTT_Helmet_4_Bw_Tropentarn",
					"TTT_Helmet_5_Bw_Tropentarn",
					"TTT_Helmet_6_Bw_Tropentarn",
					"TTT_Helmet_1_Bw_Flecktarn",
					"TTT_Helmet_2_Bw_Flecktarn",
					"TTT_Helmet_3_Bw_Flecktarn",
					"TTT_Helmet_4_Bw_Flecktarn",
					"TTT_Helmet_5_Bw_Flecktarn",
					"TTT_Helmet_6_Bw_Flecktarn"
				};
		requiredAddons[] = {"ttt_main","ttt_units_bw"};
	};
};
