#include "script_component.hpp"

class CfgPatches {
    class SUBADDON {
        // Meta information for editor
        name = COMPONENT_NAME;
        author = ECSTRING(main,TacticalTrainingTeam);
        authors[] = {"Andx", "Shiloh"};
        url = ECSTRING(main,URL);

        // Minimum compatible version. When the game's version is lower, pop-up warning will appear when launching the game. Note: was disabled on purpose some time late into Arma 2: OA.
        requiredVersion = REQUIRED_VERSION;
        // Required addons, used for setting load order. (CfgPatches classname NOT PBO filename!)
        // When any of the addons are missing, a pop-up warning will appear when launching the game.
        requiredAddons[] = {
            "ttt_compat_rhs",
            "rhsusf_main",
            "rhsusf_c_weapons",
            "rhsusf_c_troops"
        };
        // List of objects (CfgVehicles classes) contained in the addon. Important also for Zeus content (units and groups) unlocking.
        units[] = {
            //PACKS
            "rhsusf_assault_eagleaiii_ocp",
            "rhsusf_assault_eagleaiii_ocp_engineer",
            "rhsusf_assault_eagleaiii_ucp_engineer",
            "rhsusf_assault_eagleaiii_ocp_medic",
            "rhsusf_assault_eagleaiii_ucp_medic",
            "rhsusf_assault_eagleaiii_ocp_demo",
            "rhsusf_assault_eagleaiii_ucp_demo",
            "rhsusf_assault_eagleaiii_ocp_ar",
            "rhsusf_assault_eagleaiii_ucp_ar",
            "rhsusf_assault_eagleaiii_ocp_mg",
            "rhsusf_assault_eagleaiii_ucp_mg",
            "rhsusf_assault_eagleaiii_ocp_at",
            "rhsusf_assault_eagleaiii_ucp_at",
            "rhsusf_assault_eagleaiii_ucp_maaws",
            "rhsusf_assault_eagleaiii_ocp_maaws",
            "rhsusf_assault_eagleaiii_coy",
            "rhsusf_assault_eagleaiii_coy_engineer",
            "rhsusf_assault_eagleaiii_coy_demo",
            "rhsusf_assault_eagleaiii_coy_eod",
            "rhsusf_assault_eagleaiii_coy_m27",
            "rhsusf_assault_eagleaiii_coy_ar",
            "rhsusf_assault_eagleaiii_coy_mg",
            "rhsusf_assault_eagleaiii_coy_assaultman",
            "rhsusf_assault_eagleaiii_coy_at",
            "rhsusf_assault_eagleaiii_coy_aa",
            "rhsusf_falconii",
            "rhsusf_falconii_coy",
            "rhsusf_falconii_mc",
            "rhsusf_falconii_gr",
            "rhsusf_falconii_coy_gr",
            "rhsusf_falconii_gr_m32",
            "rhsusf_falconii_breach",
            "rhsusf_falconii_recon",
            "rhsusf_pack_slackman_m240",
            "rhsusf_pack_slackman_m249",
            "rhsusf_assault_eagleaiii_coy_medic",
            "rhsusf_falconii_sarc",
        };
        // List of weapons (CfgWeapons classes) contained in the addon.
        weapons[] = {
            //UNIFORMS
            "rhs_uniform_g3_mc",
            "rhs_uniform_g3_m81",
            "rhs_uniform_g3_aor2",
            "rhs_uniform_g3_tan",
            "rhs_uniform_g3_rgr",
            "rhs_uniform_g3_blk",
            "rhs_uniform_cu_ocp",
            "rhs_uniform_cu_ucp",
            "rhs_uniform_cu_ocp_1stcav",
            "rhs_uniform_cu_ucp_1stcav",
            "rhs_uniform_cu_ocp_82nd",
            "rhs_uniform_cu_ucp_82nd",
            "rhs_uniform_cu_ocp_101st",
            "rhs_uniform_cu_ucp_101st",
            "rhs_uniform_cu_ocp_10th",
            "rhs_uniform_cu_ucp_10th",
            "rhs_uniform_cu_ucp_patchless",
            "rhs_uniform_cu_ocp_patchless",
            "rhs_uniform_FROG01_d",
            "rhs_uniform_FROG01_wd",
            "rhs_uniform_FROG01_m81",
            "rhs_uniform_acu_ucp",
            "rhs_uniform_acu_ucp2",
            "rhs_uniform_acu_ucpd",
            "rhs_uniform_acu_oefcp",
            "rhs_uniform_acu_ocp",
            "rhs_uniform_abu",
            "rhs_uniform_bdu_erdl",
            //HEADGEAR
            "rhsusf_patrolcap_ocp",
            "rhs_xmas_antlers",
            "rhs_Booniehat_ocp",
            "rhs_booniehat2_marpatd",
            "rhs_8point_marpatd",
            "rhs_8point_marpatwd",
            "rhsusf_ach_helmet_ocp",
            "rhsusf_opscore_01",
            "rhsusf_opscore_cover",
            "rhsusf_opscore_mar_01",
            "rhsusf_cvc_helmet",
            "rhsusf_hgu56p",
            "rhsusf_mich_helmet_marpatwd",
            "rhsusf_mich_helmet_marpatwd_norotos_arc",
            "rhsusf_mich_bare",
            "rhsusf_mich_bare_headset",
            "rhsusf_mich_bare_alt",
            "rhsusf_mich_bare_norotos",
            "rhsusf_mich_bare_norotos_headset",
            "rhsusf_mich_bare_norotos_alt",
            "rhsusf_mich_bare_norotos_alt_headset",
            "rhsusf_mich_bare_norotos_arc",
            "rhsusf_mich_bare_norotos_arc_headset",
            "rhsusf_mich_bare_norotos_arc_alt",
            "rhsusf_mich_bare_norotos_arc_alt_headset",
            "rhsusf_mich_bare_tan",
            "rhsusf_mich_bare_tan_headset",
            "rhsusf_mich_bare_semi",
            "rhsusf_mich_bare_semi_headset",
            "rhsusf_mich_bare_norotos_semi",
            "rhsusf_mich_bare_norotos_semi_headset",
            "rhsusf_mich_bare_norotos_alt_semi",
            "rhsusf_lwh_helmet_marpatd",
            "rhsusf_Bowman",
            "rhsusf_bowman_cap",
            "RHS_jetpilot_usaf",
            "rhsusf_ihadss",
            "rhsusf_protech_helmet",
            //VESTS
            "rhsusf_iotv_ocp_base",
            "rhsusf_iotv_ocp",
            "rhsusf_iotv_ocp_Grenadier",
            "rhsusf_iotv_ocp_Medic",
            "rhsusf_iotv_ocp_Repair",
            "rhsusf_iotv_ocp_Rifleman",
            "rhsusf_iotv_ocp_SAW",
            "rhsusf_iotv_ocp_Squadleader",
            "rhsusf_iotv_ocp_Teamleader",
            "rhsusf_iotv_ucp_base",
            "rhsusf_iotv_ucp",
            "rhsusf_iotv_ucp_Grenadier",
            "rhsusf_iotv_ucp_Medic",
            "rhsusf_iotv_ucp_Repair",
            "rhsusf_iotv_ucp_Rifleman",
            "rhsusf_iotv_ucp_SAW",
            "rhsusf_spc_rifleman",
            "rhsusf_iotv_ucp_Squadleader",
            "rhsusf_spc_iar",
            "rhsusf_iotv_ucp_Teamleader",
            "rhsusf_spc_corpsman",
            "rhsusf_spc",
            "rhsusf_spc_crewman",
            "rhsusf_spc_light",
            "rhsusf_spc_marksman",
            "rhsusf_spc_mg",
            "rhsusf_spc_sniper",
            "rhsusf_spc_squadleader",
            "rhsusf_spc_teamleader",
            "rhsusf_spc_patchless",
            "rhsusf_spc_patchless_radio",
            "rhsusf_spcs_ocp",
            "rhsusf_spcs_ocp_squadleader",
            "rhsusf_spcs_ocp_teamleader",
            "rhsusf_spcs_ocp_teamleader_alt",
            "rhsusf_spcs_ocp_saw",
            "rhsusf_spcs_ocp_grenadier",
            "rhsusf_spcs_ocp_rifleman",
            "rhsusf_spcs_ocp_rifleman_alt",
            "rhsusf_spcs_ocp_medic",
            "rhsusf_spcs_ocp_crewman",
            "rhsusf_spcs_ocp_machinegunner",
            "rhsusf_spcs_ocp_sniper",
            "rhsusf_spcs_ucp",
            "rhsusf_spcs_ucp_squadleader",
            "rhsusf_spcs_ucp_teamleader",
            "rhsusf_spcs_ucp_teamleader_alt",
            "rhsusf_spcs_ucp_saw",
            "rhsusf_spcs_ucp_grenadier",
            "rhsusf_spcs_ucp_rifleman",
            "rhsusf_spcs_ucp_rifleman_alt",
            "rhsusf_spcs_ucp_medic",
            "rhsusf_spcs_ucp_crewman",
            "rhsusf_spcs_ucp_machinegunner",
            "rhsusf_spcs_ucp_sniper",
            "rhsusf_mbav",
            "rhsusf_mbav_light",
            "rhsusf_mbav_rifleman",
            "rhsusf_mbav_mg",
            "rhsusf_mbav_grenadier",
            "rhsusf_mbav_medic",
            "rhsusf_plateframe_sapi",
            "rhsusf_plateframe_light",
            "rhsusf_plateframe_rifleman",
            "rhsusf_plateframe_teamleader",
            "rhsusf_plateframe_grenadier",
            "rhsusf_plateframe_machinegunner",
            "rhsusf_plateframe_marksman",
            "rhsusf_plateframe_medic",
        };

        // Optional. If this is 1, if any of requiredAddons[] entry is missing in your game the entire config will be ignored and return no error (but in rpt) so useful to make a compat Mod (Since Arma 3 2.14)
        skipWhenMissingDependencies = 1;
        VERSION_CONFIG;

        // this prevents any patched class from requiring this addon
        addonRootClass = "A3_Characters_F";
    };
};

#include "CfgVehicles.hpp"
#include "CfgWeapons.hpp"
