name = "TTT-Mod"
author = "Tactical Training Team"
prefix = "ttt"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.publish]
description = "workshop/steam_description.md"
changelog = "CHANGELOG.md"

[files]
exclude = [
    "*.psd",
    "*.png",
    "*.tga",
]
include = [
    "meta.cpp",
    "mod.cpp",
    "authors.txt",
    "LICENSE",
    "*.paa",
    "*.jpg"
]

[properties]
url = "https://github.com/TacticalTrainingTeam/ttt_a3"

[hemtt.signing]
authority = "Tactical Training Team"
