name = "TTT-Mod"
author = "Tactical Training Team"
prefix = "ttt"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 4

[files]
exclude = [
    "*.psd",
    "*.png",
    "*.tga",
]
include = [
    "meta.cpp",
    "mod.cpp",
    "authors.txt",
    "LICENSE",
    "*.paa",
    "*.jpg"
]

[lints.sqf]
command_case = true

[lints.config.math_could_be_unquoted]
enabled = "pedantic"

[properties]
url = "https://github.com/TacticalTrainingTeam/ttt_a3"

[hemtt.signing]
authority = "Tactical Training Team"
