name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Validate Config
        run: python3 tools/config_style_checker.py
      - name: Validate Stringtables
        run: python3 tools/stringtable_validator.py
      - name: Check Strings
        run: python3 tools/check_strings.py
      - name: Check for BOM
        uses: arma-actions/bom-check@master

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT check
        run: hemtt check