name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Validate Config
        run: python3 tools/config_style_checker.py
      - name: Validate Stringtables
        run: python3 tools/stringtable_validator.py
        continue-on-error: true
      - name: Check Strings
        run: python3 tools/check_strings.py
      - name: Check for BOM
        uses: arma-actions/bom-check@master

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Release
        uses: actions/upload-artifact@v4
        with:
          name: "@ttt_a3"
          path: ".hemttout/release/*"