#https://github.com/gruppe-adler/action-release-to-steam-ws?tab=readme-ov-file
name: 'RELEASE TO STEAM WORKSHOP'

on:
  release:
    types: [published]

jobs:
  upload-to-steam:
    name: Upload to Steam Workshop
    if: ${{ !github.event.release.prerelease }} # Do not upload pre releases
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run HEMTT release
      run: hemtt release
    # - name: Build with HEMTT
    #   uses: gruppe-adler/action-release-with-hemtt@2.2.0
    #   id: build
    - name: Upload mod
      uses: gruppe-adler/action-release-to-steam-ws@v1
      with:
        file_id: 2673457154
        username: "${{ secrets.STEAM_USERNAME }}"
        password: "${{ secrets.STEAM_PASSWORD }}"
        path: "${{ steps.build.outputs.release_path }}/@${{ steps.build.outputs.mod_name }}"
        name: "${{ steps.build.outputs.mod_name }}"
        change_notes_title: "${{ github.event.release.name }}"
        change_notes: "${{ github.event.release.body }}"
